source 'http://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.4'

# Use sqlite3 as the database for Active Record
gem 'sqlite3'

# Use MySQL as the database for Active Record
#gem 'mysql2'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.3'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer',  platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
gem 'jquery-ui-rails'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0',          group: :doc

# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
gem 'spring',        group: :development

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]

#gem 'json'
#gem 'system_timer'

gem 'haml', '4.0.5'

# Gems used for mocking and stubbing while running tests
group :test do
	gem 'webmock'
	gem 'mocha'
	gem 'capybara'
	#gem 'capybara-webkit'
	gem 'headless'
	gem 'selenium-webdriver'
	gem 'ruby-prof'
end

# Use Devise for user authentication
gem 'devise'

# Use Hanna as documentation template
gem 'hanna-nouveau'#, '0.3.0'

# Use OmniAuth for authentication with other services
# (we don't use Devise's built-in since it didn't work when we tried)
gem "omniauth-facebook"
gem "omniauth-google-oauth2"
gem "omniauth-lastfm"
gem "omniauth-linkedin"
gem "omniauth-myspace"
gem "omniauth-soundcloud"
gem "omniauth-twitter"
gem "omniauth-vimeo"
gem "omniauth-vkontakte"
gem "omniauth-weibo-oauth2"
gem "omniauth-windowslive"
gem "omniauth-yahoo"
gem "omniauth-yandex"
gem "omniauth-youtube"

gem "omniauth"

# We use GeoIP so we can adjust locale depending on origin
gem 'geoip'

# Keep spam away
gem 'recaptcha', :require => 'recaptcha/rails'

# Let third parties access our services via OAuth
gem "oauth-plugin"

# Push changes to connected clients
gem "juggernaut"

# Translate the URLs
#gem "i18n_routing"

# Paginate
gem "will_paginate"

# Audio processing
#gem "ruby-audio"
#gem "fftw3"
#gem "ruby-echonest"

# Access wikipedia API
gem "wikipedia-client"
gem "mediacloth"
gem "wikicloth"

# Truncate HTML
#gem "truncate_html"

gem "deep_merge"
gem "htmlentities"
gem 'haversine'
gem 'ruby-duration'
gem 'fastimage'
